name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create .env File
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "VITE_BASE_URL=https://dev.salimon.net/nexus" > .env
          else
            echo "VITE_BASE_URL=https://dev.salimon.net/nexus" > .env
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            pitronumdev/nexus-admin-webapp:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
      - name: Rollout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLUSTER_HOST }}
          username: ${{ secrets.CLUSTER_USERNAME }}
          key: ${{ secrets.CLUSTER_SSH_KEY }}
          port: 22
          script: kubectl rollout restart deployment/prod-nexus-admin-webapp
